* CS4032-DistributedFileSystem

[[https://travis-ci.org/KillianDavitt/CS4032-DistributedFileSystem][https://travis-ci.org/KillianDavitt/CS4032-DistributedFileSystem.svg?branch=master]]

**Project not yet completed, expected completion: 4th Feb**

This is the repository for my CS4032 - Distributed Systems project: A distributed file system

The final report can be found in [[file:./report/report.org][report.org]]

general protocol notes and thoughts can be found in [[file:notes/][notes/]]

* Running the services

#+BEGIN_SRC bash

# Complete each action in a seperate terminal session

cd authServer
docker-compose up

cd dirServer
docker-compose up

cd fileServer
docker-compose up

cd lockServer 
docker-compose up

cd transactionServer
docker-compose up

cd client
docker-compose run client -rn # This is important
#+END_SRC

* Timeline
- 27/11/16: After much pen and paper work, I've begun putting my protocol design into a document on the repo. Ideally very minimal coding will be done before I finish this spec.
- 21/01/17: Auth Server almost completed. client sign in working over TLS. Token creation by authServer completed.
- 23/01/17: Full file io working
- 25/01/17: Lock server completed with advisory locking scheme
- 25/01/17: Caching working
- 26/01/17: Basic framework for gossip protocol in place
