version: "2"
services:
  app:
    build: .
    volumes:
      - .:/home/killian/go/src/github.com/KillianDavitt/CS4032-DistributedFileSystem/fs2
      - /go:/home/killian/go
    links:
      - redis
  
  redis:
    image: redis:alpine
